[global]
disableWatchdogWarning = true

[server]
headless = true
address = "0.0.0.0"
port = 5000
enableStaticServing = true
showWarningOnDirectExecution = false

[client]
toolbarMode = "minimal"  # Hides the three-dot menu
